version: '3.8'

services:
  backend:
    build: .
    container_name: dotarank-backend
    ports:
      - "5500:5500"
    volumes:
      # Map local 'data' folder to '/data' in container for DB persistence
      - ./data:/data
    env_file:
      - .env.prod
    environment:
      - NODE_ENV=production
      - DB_PATH=/data/steam_friends.db
    restart: unless-stopped
