name: Node CI/CD VPS

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create data directory if not exists
        run: |
          mkdir -p data

      - name: Build and run with Docker Compose
        run: |
          docker-compose down
          docker-compose up --build -d

      - name: Wait for service
        run: |
          sleep 5

      - name: Smoke test
        run: |
          curl -f http://localhost:5500/dota || exit 1
